# Site settings
title: Crook & Mayor
email: me@ivanodbratt.com
description: ""
baseurl: ""
url: "http://crookandmayor.com"


# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
encoding: utf-8
